# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-node

    steps:
      - add_ssh_keys:
        fingerprints:
          - 'bf:45:48:f7:6a:d8:9f:32:5d:54:e9:a7:96:6c:af:4b'
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn test
      - run: yarn deploy
