# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-node

    steps:
      - add_ssh_keys:
          fingerprints:
            - '42:ee:f7:29:fc:7f:33:a6:ef:68:28:99:68:ba:fc:b7'
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn test
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
      - run: yarn deploy
